//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
//Emily Quevedo and Almicke Navarro 
//CST 247
//Milestone 1
//January 23, 2019

namespace MinesweeperWeb.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class user
    {
        public string RegisterSuccess { get; set; }

        public string RegisterFail { get; set; }

        public string LoginErrorMessage { get; set; }

        public int id { get; set; }

        [DisplayName("First Name: ")]
        [Required(ErrorMessage = "*This field is required")]
        public string firstname { get; set; }

        [DisplayName("Last Name: ")]
        [Required(ErrorMessage = "*This field is required")]
        public string lastname { get; set; }

        [DisplayName("Sex: ")]
        [Required(ErrorMessage = "*This field is required")]
        public string sex { get; set; }

        [DisplayName("Age: ")]
        [Required(ErrorMessage = "*This field is required")]
        public string age { get; set; }

        [DisplayName("State: ")]
        [Required(ErrorMessage = "*This field is required")]
        public string state { get; set; }

        [DisplayName("E-mail: ")]
        [Required(ErrorMessage = "*This field is required")]
        public string email { get; set; }

        [DisplayName("Username: ")]
        [Required(ErrorMessage = "*This field is required")]
        public string username { get; set; }

        [DisplayName("Password: ")]
        [Required(ErrorMessage = "*This field is required")]
        public string password { get; set; }
    }
}
